In [1]:
x <- c(2, 4, 6, 8)
y <- c(10, 12, 14, 16)
z <- c(18, 20, 22, 24)

In [2]:
cbind(x, y, z)

x y  z 
[1,] 2 10 18
[2,] 4 12 20
[3,] 6 14 22
[4,] 8 16 24

In [6]:
matrix(c(2, 10, 18,
        4, 12, 20,
        6, 14, 22,
        8, 16, 24), nrow=4, byrow=T)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [7]:
matrix(c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24), nrow=4)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [8]:
x <- c(9, 7, 5, 3)
y <- c(8, 11, 2, 9)

In [10]:
m <- rbind(x, y)
m

[,1] [,2] [,3] [,4]
x 9     7   5    3   
y 8    11   2    9

In [11]:
rownames(m) <- c('x', '
y')

In [12]:
colnames(m) <- c('a', 'b', 'c', 'd')

In [13]:
m

a b  c d
x   9  7 5 3
\ny 8 11 2 9

In [14]:
blood <- c('A', 'O', 'AB', 'B', 'B')
rh <- c('+', '+', '-', '+', '+')
age <- c(21, 30, 43, 17, 26)

In [15]:
df <- data.frame(blood, rh, age)

In [16]:
df

blood rh age
1 A     +  21 
2 O     +  30 
3 AB    -  43 
4 B     +  17 
5 B     +  26

In [17]:
colnames(df)

[1] "blood" "rh"    "age"

In [ ]:
df['blood']

In [24]:
df.nb <- df[df$blood != 'B', ]

In [25]:
df.nb

blood rh age
1 A     +  21 
2 O     +  30 
3 AB    -  43

In [26]:
df = cars

In [27]:
dim(df)

[1] 50  2

In [28]:
number <- 1:7
title <- c('1', '2', '3', '4', '5', '6', '7')
like <- c(16075, 8218, 12119, 738, 3200, 16144, 5110)
love <- data.frame(number, title, like)

In [29]:
love

number title like 
1 1      1     16075
2 2      2      8218
3 3      3     12119
4 4      4       738
5 5      5      3200
6 6      6     16144
7 7      7      5110

In [31]:
love[love$like == max(love$like), ]

number title like 
6 6      6     16144

In [32]:
best <- rownames(love[love$like == max(love$like), ])
best

[1] "6"

In [33]:
class(cars)

[1] "data.frame"

In [34]:
dim(cars)

[1] 50  2

In [35]:
head(cars)

speed dist
1 4      2  
2 4     10  
3 7      4  
4 7     22  
5 8     16  
6 9     10

In [36]:
str(cars)

'data.frame':	50 obs. of  2 variables:
 $ speed: num  4 4 7 7 8 9 10 10 10 11 ...
 $ dist : num  2 10 4 22 16 10 18 26 34 17 ...


In [37]:
colMeans(cars)

speed  dist 
15.40 42.98

In [38]:
apply(cars, 2, mean)

speed  dist 
15.40 42.98

In [40]:
cars[cars$dist == max(cars$dist), 'dist']

[1] 120

In [41]:
cars[cars$dist == max(cars$dist), ]

speed dist
49 24    120

In [42]:
cars[cars$dist == max(cars$dist), ][c('speed', 'dist')]

speed dist
49 24    120