In [1]:
x <- c(2, 4, 6, 8)
y <- c(10, 12, 14, 16)
z <- c(18, 20, 22, 24)

In [2]:
cbind(x, y, z)

x y  z 
[1,] 2 10 18
[2,] 4 12 20
[3,] 6 14 22
[4,] 8 16 24

In [6]:
matrix(c(2, 10, 18,
        4, 12, 20,
        6, 14, 22,
        8, 16, 24), nrow=4, byrow=T)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [7]:
matrix(c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24), nrow=4)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [8]:
x <- c(9, 7, 5, 3)
y <- c(8, 11, 2, 9)

In [10]:
m <- rbind(x, y)
m

[,1] [,2] [,3] [,4]
x 9     7   5    3   
y 8    11   2    9

In [11]:
rownames(m) <- c('x', '
y')

In [12]:
colnames(m) <- c('a', 'b', 'c', 'd')

In [13]:
m

a b  c d
x   9  7 5 3
\ny 8 11 2 9

In [14]:
blood <- c('A', 'O', 'AB', 'B', 'B')
rh <- c('+', '+', '-', '+', '+')
age <- c(21, 30, 43, 17, 26)

In [15]:
df <- data.frame(blood, rh, age)

In [16]:
df

blood rh age
1 A     +  21 
2 O     +  30 
3 AB    -  43 
4 B     +  17 
5 B     +  26

In [17]:
colnames(df)

[1] "blood" "rh"    "age"

In [ ]:
df['blood']

In [24]:
df.nb <- df[df$blood != 'B', ]

In [25]:
df.nb

blood rh age
1 A     +  21 
2 O     +  30 
3 AB    -  43

In [26]:
df = cars

In [27]:
dim(df)

[1] 50  2

In [28]:
number <- 1:7
title <- c('1', '2', '3', '4', '5', '6', '7')
like <- c(16075, 8218, 12119, 738, 3200, 16144, 5110)
love <- data.frame(number, title, like)

In [29]:
love

number title like 
1 1      1     16075
2 2      2      8218
3 3      3     12119
4 4      4       738
5 5      5      3200
6 6      6     16144
7 7      7      5110

In [31]:
love[love$like == max(love$like), ]

number title like 
6 6      6     16144

In [32]:
best <- rownames(love[love$like == max(love$like), ])
best

[1] "6"

In [33]:
class(cars)

[1] "data.frame"

In [34]:
dim(cars)

[1] 50  2

In [35]:
head(cars)

speed dist
1 4      2  
2 4     10  
3 7      4  
4 7     22  
5 8     16  
6 9     10

In [36]:
str(cars)

'data.frame':	50 obs. of  2 variables:
 $ speed: num  4 4 7 7 8 9 10 10 10 11 ...
 $ dist : num  2 10 4 22 16 10 18 26 34 17 ...


In [37]:
colMeans(cars)

speed  dist 
15.40 42.98

In [38]:
apply(cars, 2, mean)

speed  dist 
15.40 42.98

In [40]:
cars[cars$dist == max(cars$dist), 'dist']

[1] 120

In [41]:
cars[cars$dist == max(cars$dist), ]

speed dist
49 24    120

In [42]:
cars[cars$dist == max(cars$dist), ][c('speed', 'dist')]

speed dist
49 24    120

In [43]:
25 + 99

[1] 124

In [44]:
2 * (3 + 4)

[1] 14

In [45]:
(7-4) * 3

[1] 9

In [46]:
1256 %% 7

[1] 3

In [47]:
1976 / 24

[1] 82.33333

In [49]:
pi <- 3.14
round <- c(10, 12, 15)
for(i in 1:3){
    cat("반지름이 ", round[i], "인 원의 면적 : ", pi * (round[i] ^ 2), '\n')
}

반지름이  10 인 원의 면적 :  314 
반지름이  12 인 원의 면적 :  452.16 
반지름이  15 인 원의 면적 :  706.5 


In [50]:
vc.2 <- seq(100, 200, 2)

In [51]:
vc.2

[1] 100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136
[20] 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174
[39] 176 178 180 182 184 186 188 190 192 194 196 198 200

In [52]:
d <- 100:200

In [53]:
d

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 [19] 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 [37] 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 [55] 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 [73] 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 [91] 190 191 192 193 194 195 196 197 198 199 200

In [54]:
d[10]

[1] 109

In [55]:
d[91:100]

[1] 190 191 192 193 194 195 196 197 198 199

In [56]:
d[d%%2 == 1]

[1] 101 103 105 107 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137
[20] 139 141 143 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175
[39] 177 179 181 183 185 187 189 191 193 195 197 199

In [57]:
d[d%%3 == 0]

[1] 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156
[20] 159 162 165 168 171 174 177 180 183 186 189 192 195 198

In [58]:
d.20 <- d[1:20]

In [59]:
d.20

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119

In [60]:
d.20[ - 5]

[1] 100 101 102 103 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119

In [61]:
d.20[-c(5, 7, 9)]

[1] 100 101 102 103 105 107 109 110 111 112 113 114 115 116 117 118 119

In [62]:
d1 <- 1:50
d2 <- 51:100

In [63]:
d1

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

In [64]:
d2

[1]  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69
[20]  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
[39]  89  90  91  92  93  94  95  96  97  98  99 100

In [65]:
length(d2)

[1] 50

In [66]:
d1 + d2

[1]  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86  88
[20]  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120 122 124 126
[39] 128 130 132 134 136 138 140 142 144 146 148 150

In [67]:
abs(d2-d1)

[1] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
[26] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50

In [68]:
d1 * d2

[1]   51  104  159  216  275  336  399  464  531  600  671  744  819  896  975
[16] 1056 1139 1224 1311 1400 1491 1584 1679 1776 1875 1976 2079 2184 2291 2400
[31] 2511 2624 2739 2856 2975 3096 3219 3344 3471 3600 3731 3864 3999 4136 4275
[46] 4416 4559 4704 4851 5000

In [69]:
d2 / d1

[1] 51.000000 26.000000 17.666667 13.500000 11.000000  9.333333  8.142857
 [8]  7.250000  6.555556  6.000000  5.545455  5.166667  4.846154  4.571429
[15]  4.333333  4.125000  3.941176  3.777778  3.631579  3.500000  3.380952
[22]  3.272727  3.173913  3.083333  3.000000  2.923077  2.851852  2.785714
[29]  2.724138  2.666667  2.612903  2.562500  2.515152  2.470588  2.428571
[36]  2.388889  2.351351  2.315789  2.282051  2.250000  2.219512  2.190476
[43]  2.162791  2.136364  2.111111  2.086957  2.063830  2.041667  2.020408
[50]  2.000000

In [70]:
sum(d1)

[1] 1275

In [71]:
sum(d2)

[1] 3775

In [72]:
max(d2)

[1] 100

In [73]:
min(d2)

[1] 51

In [74]:
mean(d2) - mean(d1)

[1] 50

In [75]:
sort(d1, T)

[1] 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
[26] 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1

In [76]:
d3 <- c(d1[1:10], d2[1:10])

In [77]:
d3

[1]  1  2  3  4  5  6  7  8  9 10 51 52 53 54 55 56 57 58 59 60

In [78]:
length(d3)

[1] 20

In [79]:
a <- c('Korea', 'Japan', 'China', 'Korea', 'India', 'China', 'Korea')
f <- factor(a)

In [80]:
f

[1] Korea Japan China Korea India China Korea
Levels: China India Japan Korea

In [81]:
f[[4]]

[1] Korea
Levels: China India Japan Korea

In [82]:
class(f[[4]])

[1] "factor"

In [83]:
as.integer(f[[4]])

[1] 4