In [1]:
x <- c(2, 4, 6, 8)
y <- c(10, 12, 14, 16)
z <- c(18, 20, 22, 24)
m <- data.frame(x, y,z)
m

x y  z 
1 2 10 18
2 4 12 20
3 6 14 22
4 8 16 24

In [2]:
matrix(c(2, 10, 18, 4, 12, 20, 6, 14, 22, 8, 16, 24), nrow=4, byrow=T)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [3]:
matrix(c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24), nrow=4)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [4]:
m <- matrix(c(9, 7, 5, 3, 8, 11, 2, 9), nrow=2, byrow=T)
m

[,1] [,2] [,3] [,4]
[1,] 9     7   5    3   
[2,] 8    11   2    9

In [6]:
rownames(m) <- c('x', 'y')
colnames(m) <- c('a', 'b', 'c', 'd')

In [7]:
m

a b  c d
x 9  7 5 3
y 8 11 2 9

In [8]:
t(m)

x y 
a 9  8
b 7 11
c 5  2
d 3  9

In [9]:
df <- data.frame(m)
df

a b  c d
x 9  7 5 3
y 8 11 2 9

In [10]:
df['info'] <- c(2, 4, 5, 6)

ERROR: Error in `[<-.data.frame`(`*tmp*`, "info", value = c(2, 4, 5, 6)): replacement has 4 rows, data has 2


In [11]:
info <- c(1, 2, 4, 8)

In [12]:
df.new <- data.frame(df, info)

Warning message in data.frame(df, info):
"row names were found from a short variable and have been discarded"


In [13]:
df.new

a b  c d info
1 9  7 5 3 1   
2 8 11 2 9 2   
3 9  7 5 3 4   
4 8 11 2 9 8

In [14]:
blood <- c('A', 'O', 'AB', 'B', 'B')
rh <- c('+', '+', '-', '+', '+')
age <- c(21, 30, 43, 17, 26)
df <- data.frame(blood, rh, age)

In [15]:
df

blood rh age
1 A     +  21 
2 O     +  30 
3 AB    -  43 
4 B     +  17 
5 B     +  26

In [16]:
df[df['blood'] != 'B', ]

blood rh age
1 A     +  21 
2 O     +  30 
3 AB    -  43

In [17]:
df = cars

In [18]:
dim(df)

[1] 50  2

In [19]:
str(df)

'data.frame':	50 obs. of  2 variables:
 $ speed: num  4 4 7 7 8 9 10 10 10 11 ...
 $ dist : num  2 10 4 22 16 10 18 26 34 17 ...


In [20]:
n <- 1:7
n.2 <- c('1', '2', '3', '4', '5', '6', '7')
n.3 <- c(100,200,300,400,500,600,700)

In [21]:
m <- data.frame(n, n.2, n.3)
m

n n.2 n.3
1 1 1   100
2 2 2   200
3 3 3   300
4 4 4   400
5 5 5   500
6 6 6   600
7 7 7   700

In [23]:
m[m['n.3'] == max(m['n.3']), ]

n n.2 n.3
7 7 7   700

In [24]:
best <- m[m['n.3'] == max(m['n.3']), ]

In [26]:
best

n n.2 n.3
7 7 7   700

In [27]:
df = cars

In [28]:
class(df)

[1] "data.frame"

In [29]:
dim(df)

[1] 50  2

In [30]:
head(df)

speed dist
1 4      2  
2 4     10  
3 7      4  
4 7     22  
5 8     16  
6 9     10

In [31]:
str(df)

'data.frame':	50 obs. of  2 variables:
 $ speed: num  4 4 7 7 8 9 10 10 10 11 ...
 $ dist : num  2 10 4 22 16 10 18 26 34 17 ...


In [32]:
colMeans(df)

speed  dist 
15.40 42.98

In [33]:
max(df$dist)

[1] 120

In [35]:
df[df['dist'] == max(df['dist']), ]

speed dist
49 24    120