In [1]:
x <- c(2, 4, 6, 8)
y <- c(10, 12, 14, 16)
z <- c(18, 20, 22, 24)
m <- cbind(x, y, z)

In [2]:
m

x y  z 
[1,] 2 10 18
[2,] 4 12 20
[3,] 6 14 22
[4,] 8 16 24

In [3]:
matrix(c(2, 10, 18, 4, 12, 20, 6, 14, 22, 8, 16, 24), nrow=4, byrow=T)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [4]:
matrix(c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24), ncol=3)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [5]:
m <- matrix(c(9, 8, 7, 11, 5, 2, 3, 9), nrow=2, byrow=T)
m

[,1] [,2] [,3] [,4]
[1,] 9    8    7    11  
[2,] 5    2    3     9

In [6]:
rownames(m) <- c('x',' y')
colnames(m) <- c('a', 'b', 'c', 'd')

In [7]:
m
# 단순 매트릭스에도 데이터 프레임처럼 1차원 벡터가 아니기에, rownames, colnames 사용 가능

a b c d 
x  9 8 7 11
 y 5 2 3  9

In [8]:
번호 <- 1:7
제목 <- c("그대랑", '다툼', '빨래', '두통', '보조개', '매듭', '이상해')
좋아요 <- c(16075, 8218, 12119, 738, 3200, 16144, 5100)
love <- data.frame(번호, 제목, 좋아요)
love

번호 제목   좋아요
1 1    그대랑 16075 
2 2    다툼    8218 
3 3    빨래   12119 
4 4    두통     738 
5 5    보조개  3200 
6 6    매듭   16144 
7 7    이상해  5100

In [11]:
best <- love[love['좋아요'] == max(love['좋아요']), ] 
best

번호 제목 좋아요
6 6    매듭 16144

In [12]:
df = cars

In [13]:
class(df)

[1] "data.frame"

In [14]:
dim(df)

[1] 50  2

In [15]:
head(df)

speed dist
1 4      2  
2 4     10  
3 7      4  
4 7     22  
5 8     16  
6 9     10

In [16]:
str(df)

'data.frame':	50 obs. of  2 variables:
 $ speed: num  4 4 7 7 8 9 10 10 10 11 ...
 $ dist : num  2 10 4 22 16 10 18 26 34 17 ...


In [17]:
colMeans(df)

speed  dist 
15.40 42.98

In [18]:
df[df['dist'] == max(df['dist']), ]

speed dist
49 24    120

In [19]:
25 + 99 
2 * ( 3 + 4 )
( 7 - 4 ) * 3
1256 %% 7
1976 / 24

[1] 124

[1] 14

[1] 9

[1] 3

[1] 82.33333

In [21]:
round <- c(10, 12, 15)
pi <- 3.14
for(i in 1:3){
    cat("반지름이 ",round[i], "인 원의 면적 : ", pi * (round[i] ^ 2), "\n")
}

반지름이  10 인 원의 면적 :  314 
반지름이  12 인 원의 면적 :  452.16 
반지름이  15 인 원의 면적 :  706.5 


In [22]:
vc.2 <- seq(100, 200, 2)
vc.2

[1] 100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136
[20] 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174
[39] 176 178 180 182 184 186 188 190 192 194 196 198 200

In [23]:
d <- 1:200
d

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
[109] 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
[127] 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
[145] 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
[163] 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
[181] 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
[199] 199 200

In [24]:
d[10]

[1] 10

In [25]:
d[91:100]

[1]  91  92  93  94  95  96  97  98  99 100

In [26]:
d[d%%2 == 1]

[1]   1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
 [19]  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
 [37]  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 [55] 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 [73] 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 [91] 181 183 185 187 189 191 193 195 197 199

In [27]:
d[d%%3 ==0]

[1]   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54  57
[20]  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108 111 114
[39] 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171
[58] 174 177 180 183 186 189 192 195 198

In [28]:
d.20 <- d[1:20]
d.20

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [29]:
d.20[-5]

[1]  1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [30]:
d.20[-c(5, 7, 9)]

[1]  1  2  3  4  6  8 10 11 12 13 14 15 16 17 18 19 20

In [31]:
d1 <- 1:50
d2 <- 51:100

In [32]:
d1

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

In [33]:
d2

[1]  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69
[20]  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
[39]  89  90  91  92  93  94  95  96  97  98  99 100

In [34]:
length(d1)
length(d2)

[1] 50

[1] 50

In [35]:
d1 + d2
d2 - d1
d1 * d2
d2 / d1

[1]  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86  88
[20]  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120 122 124 126
[39] 128 130 132 134 136 138 140 142 144 146 148 150

[1] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
[26] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50

[1]   51  104  159  216  275  336  399  464  531  600  671  744  819  896  975
[16] 1056 1139 1224 1311 1400 1491 1584 1679 1776 1875 1976 2079 2184 2291 2400
[31] 2511 2624 2739 2856 2975 3096 3219 3344 3471 3600 3731 3864 3999 4136 4275
[46] 4416 4559 4704 4851 5000

[1] 51.000000 26.000000 17.666667 13.500000 11.000000  9.333333  8.142857
 [8]  7.250000  6.555556  6.000000  5.545455  5.166667  4.846154  4.571429
[15]  4.333333  4.125000  3.941176  3.777778  3.631579  3.500000  3.380952
[22]  3.272727  3.173913  3.083333  3.000000  2.923077  2.851852  2.785714
[29]  2.724138  2.666667  2.612903  2.562500  2.515152  2.470588  2.428571
[36]  2.388889  2.351351  2.315789  2.282051  2.250000  2.219512  2.190476
[43]  2.162791  2.136364  2.111111  2.086957  2.063830  2.041667  2.020408
[50]  2.000000

In [36]:
sum(d2)

[1] 3775

In [37]:
sum(d1)

[1] 1275

In [38]:
mean(d2) - mean(d1)

[1] 50

In [39]:
sort(d1, T)

[1] 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
[26] 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1

In [40]:
d3 <- c(d1[1:10], d2[1:10])

In [41]:
d3

[1]  1  2  3  4  5  6  7  8  9 10 51 52 53 54 55 56 57 58 59 60

In [42]:
a <- c('Korea', 'Japan', 'China', 'Korea', 'India', 'China', 'Korea')
f <- factor(a)

In [43]:
class(f)

[1] "factor"

In [45]:
f

[1] Korea Japan China Korea India China Korea
Levels: China India Japan Korea

In [46]:
f[[4]]

[1] Korea
Levels: China India Japan Korea

In [47]:
class(f[[4]])

[1] "factor"

In [48]:
as.numeric(f[[4]])

[1] 4

In [49]:
class(as.numeric(f[[4]]))

[1] "numeric"