In [1]:
x <- c(2, 4, 6, 8)
y <- c(10, 12, 14, 16)
z <- c(18, 20, 22, 24)
m <- cbind(x, y, z)

In [2]:
m

x y  z 
[1,] 2 10 18
[2,] 4 12 20
[3,] 6 14 22
[4,] 8 16 24

In [3]:
matrix(c(2, 10, 18, 4, 12, 20, 6, 14, 22, 8, 16, 24), nrow=4, byrow=T)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [4]:
matrix(c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24), ncol=3)

[,1] [,2] [,3]
[1,] 2    10   18  
[2,] 4    12   20  
[3,] 6    14   22  
[4,] 8    16   24

In [5]:
m <- matrix(c(9, 8, 7, 11, 5, 2, 3, 9), nrow=2, byrow=T)
m

[,1] [,2] [,3] [,4]
[1,] 9    8    7    11  
[2,] 5    2    3     9

In [6]:
rownames(m) <- c('x',' y')
colnames(m) <- c('a', 'b', 'c', 'd')

In [7]:
m
# 단순 매트릭스에도 데이터 프레임처럼 1차원 벡터가 아니기에, rownames, colnames 사용 가능

a b c d 
x  9 8 7 11
 y 5 2 3  9

In [8]:
번호 <- 1:7
제목 <- c("그대랑", '다툼', '빨래', '두통', '보조개', '매듭', '이상해')
좋아요 <- c(16075, 8218, 12119, 738, 3200, 16144, 5100)
love <- data.frame(번호, 제목, 좋아요)
love

번호 제목   좋아요
1 1    그대랑 16075 
2 2    다툼    8218 
3 3    빨래   12119 
4 4    두통     738 
5 5    보조개  3200 
6 6    매듭   16144 
7 7    이상해  5100

In [11]:
best <- love[love['좋아요'] == max(love['좋아요']), ] 
best

번호 제목 좋아요
6 6    매듭 16144