In [1]:
unique(iris[, -5])

Sepal.Length Sepal.Width Petal.Length Petal.Width
1   5.1          3.5         1.4          0.2        
2   4.9          3.0         1.4          0.2        
3   4.7          3.2         1.3          0.2        
4   4.6          3.1         1.5          0.2        
5   5.0          3.6         1.4          0.2        
6   5.4          3.9         1.7          0.4        
7   4.6          3.4         1.4          0.3        
8   5.0          3.4         1.5          0.2        
9   4.4          2.9         1.4          0.2        
10  4.9          3.1         1.5          0.1        
11  5.4          3.7         1.5          0.2        
12  4.8          3.4         1.6          0.2        
13  4.8          3.0         1.4          0.1        
14  4.3          3.0         1.1          0.1        
15  5.8          4.0         1.2          0.2        
16  5.7          4.4         1.5          0.4        
17  5.4          3.9         1.3          0.4        
18  5.1          3.5         1.4          0.3        
19  5.7          3.8         1.7          0.3        
20  5.1          3.8         1.5          0.3        
21  5.4          3.4         1.7          0.2        
22  5.1          3.7         1.5          0.4        
23  4.6          3.6         1.0          0.2        
24  5.1          3.3         1.7          0.5        
25  4.8          3.4         1.9          0.2        
26  5.0          3.0         1.6          0.2        
27  5.0          3.4         1.6          0.4        
28  5.2          3.5         1.5          0.2        
29  5.2          3.4         1.4          0.2        
30  4.7          3.2         1.6          0.2        
⋮   ⋮            ⋮           ⋮            ⋮          
120 6.0          2.2         5.0          1.5        
121 6.9          3.2         5.7          2.3        
122 5.6          2.8         4.9          2.0        
123 7.7          2.8         6.7          2.0        
124 6.3          2.7         4.9          1.8        
125 6.7          3.3         5.7          2.1        
126 7.2          3.2         6.0          1.8        
127 6.2          2.8         4.8          1.8        
128 6.1          3.0         4.9          1.8        
129 6.4          2.8         5.6          2.1        
130 7.2          3.0         5.8          1.6        
131 7.4          2.8         6.1          1.9        
132 7.9          3.8         6.4          2.0        
133 6.4          2.8         5.6          2.2        
134 6.3          2.8         5.1          1.5        
135 6.1          2.6         5.6          1.4        
136 7.7          3.0         6.1          2.3        
137 6.3          3.4         5.6          2.4        
138 6.4          3.1         5.5          1.8        
139 6.0          3.0         4.8          1.8        
140 6.9          3.1         5.4          2.1        
141 6.7          3.1         5.6          2.4        
142 6.9          3.1         5.1          2.3        
144 6.8          3.2         5.9          2.3        
145 6.7          3.3         5.7          2.5        
146 6.7          3.0         5.2          2.3        
147 6.3          2.5         5.0          1.9        
148 6.5          3.0         5.2          2.0        
149 6.2          3.4         5.4          2.3        
150 5.9          3.0         5.1          1.8

In [2]:
unique(iris[, 5])

[1] setosa     versicolor virginica 
Levels: setosa versicolor virginica

In [3]:
table(iris[ , 5])


    setosa versicolor  virginica 
        50         50         50 

In [4]:
score <- c(76, 84, 69, 50, 95, 60, 82, 71, 88, 84)

In [6]:
which(score == 69)

[1] 3

In [7]:
which(score > 85)

[1] 5 9

In [8]:
which.max(score)

[1] 5

In [9]:
score[5]

[1] 95

In [10]:
max(score)

[1] 95

In [11]:
which.min(score)

[1] 4

In [12]:
score[4]

[1] 50

In [13]:
min(score)

[1] 50

In [16]:
which(score <= 60)

[1] 4 6

In [17]:
score[c(4, 6)]

[1] 50 60

In [19]:
score[which(score <= 60)] <- 61

In [20]:
score

[1] 76 84 69 61 95 61 82 71 88 84

In [23]:
which(score >= 80)

[1]  2  5  7  9 10

In [24]:
idx <- score[which(score >= 80)]
idx

[1] 84 95 82 88 84

In [25]:
score <- c(60, 40, 95, 80)
score

[1] 60 40 95 80

In [26]:
names(score) <- c('John', 'Jane', 'Tom', 'David')

In [27]:
score

John  Jane   Tom David 
   60    40    95    80

In [28]:
score[which.max(score)]

Tom 
 95

In [29]:
z <- matrix(1:20, nrow=4) 
z

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [32]:
x <- 1:4
y <- 5:8
z <- matrix(1:20, nrow=4)
cbind(x, y)
rbind(x, y)
cbind(x, y, z)

x y
[1,] 1 5
[2,] 2 6
[3,] 3 7
[4,] 4 8

[,1] [,2] [,3] [,4]
x 1    2    3    4   
y 5    6    7    8

x y             
[1,] 1 5 1 5  9 13 17
[2,] 2 6 2 6 10 14 18
[3,] 3 7 3 7 11 15 19
[4,] 4 8 4 8 12 16 20

In [33]:
rbind(x, y, z)

Warning message in rbind(x, y, z):
"number of columns of result is not a multiple of vector length (arg 1)"


[,1] [,2] [,3] [,4] [,5]
x 1    2     3    4    1  
y 5    6     7    8    5  
  1    5     9   13   17  
  2    6    10   14   18  
  3    7    11   15   19  
  4    8    12   16   20

In [34]:
z <- matrix(1:20, nrow=4, ncol=5)
z

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [35]:
z[2, 1:3]

[1]  2  6 10

In [36]:
z[1, c(1, 2, 4)]

[1]  1  5 13

In [37]:
z[1:2]

[1] 1 2

In [38]:
z[1:2,]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18

In [40]:
z[, c(1, 4)]

[,1] [,2]
[1,] 1    13  
[2,] 2    14  
[3,] 3    15  
[4,] 4    16

In [42]:
score <- matrix(c(90, 85, 69, 78, 85, 96, 49, 95, 90, 80, 70, 60), nrow=4)

In [43]:
score

[,1] [,2] [,3]
[1,] 90   85   90  
[2,] 85   96   80  
[3,] 69   49   70  
[4,] 78   95   60

In [44]:
rownames(score) <- c('John', 'Tom', 'Mark', 'Jane')

In [45]:
colnames(score) <- c('English', 'Math', 'Science')

In [46]:
score

English Math Science
John 90      85   90     
Tom  85      96   80     
Mark 69      49   70     
Jane 78      95   60