In [1]:
a <- 10
b <- 20
c <- a + b
c

[1] 30

In [2]:
a <- 125
a

[1] 125

In [3]:
a <- 10
b <- 20
a + b
a <- 'A'
a + b

[1] 30

ERROR: Error in a + b: non-numeric argument to binary operator


In [4]:
x <- c(1, 2, 3)
y <- c("a", "b", "c")
z <- c(TRUE, TRUE, FALSE, TRUE)
x
y
z

[1] 1 2 3

[1] "a" "b" "c"

[1]  TRUE  TRUE FALSE  TRUE

In [5]:
w <- c(1, 2, 3, "a", "b", "c")
w

[1] "1" "2" "3" "a" "b" "c"

In [6]:
class(w)

[1] "character"

In [7]:
w.a <- c(1, 2, 3)
class(w.a)

[1] "numeric"

In [9]:
v1 <- 50:90
v1

[1] 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
[26] 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90

In [10]:
v2 <- c(1, 2, 5, 51:90)
v2

[1]  1  2  5 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
[26] 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90

In [12]:
v3 <- seq(1, 101, 3)
v3

[1]   1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52  55
[20]  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100

In [13]:
# 특정한 간격을 두고 벡터 생성 : seq
v4 <- seq(0.1, 1.0, 0.1)
v4

[1] 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

In [14]:
# 반복된 숫자로 이루어진 벡터 생성
v5 <- rep(1, 5)
v5

[1] 1 1 1 1 1

In [16]:
v6 <- rep(1:5, 3)
v6

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

In [18]:
v7 <- rep(c(1, 5, 9), 3)
v7

[1] 1 5 9 1 5 9 1 5 9

In [19]:
score <- c(90, 85, 70)
score

[1] 90 85 70

In [20]:
names(score) <- c("Layla","focalors", "alice")
score

Layla focalors    alice 
      90       85       70

In [21]:
d <- c(1, 4, 3, 7, 8)
d

[1] 1 4 3 7 8

In [22]:
d[1]

[1] 1

In [23]:
d[2]

[1] 4

In [24]:
d[3]

[1] 3

In [25]:
d[4]

[1] 7

In [26]:
d[5]

[1] 8

In [30]:
for(i in 1:length(d)){
    cat(d[i], "\n")
}

1 
4 
3 
7 
8 


In [31]:
d <- c(1, 4, 3, 7, 8)
d[6]
# 인덱스에 없는 값을 요청하면, <NA>반환

[1] NA

In [32]:
d <- c(1, 4, 3, 7, 8)
d[c(1, 3, 5)]

[1] 1 3 8

In [33]:
d[1:3]

[1] 1 4 3

In [34]:
d[seq(1, 5, 2)]

[1] 1 3 8

In [35]:
d[-2]

[1] 1 3 7 8

In [36]:
d[-c(3, 5)]

[1] 1 4 7

In [37]:
GNP <- c(2090, 2450, 960)
GNP

[1] 2090 2450  960

In [38]:
names(GNP) <- c("Korea", "Japan", "Nepal")
GNP

Korea Japan Nepal 
 2090  2450   960

In [39]:
GNP[1]

Korea 
 2090

In [40]:
GNP[2]

Japan 
 2450

In [41]:
GNP['Nepal']

Nepal 
  960

In [42]:
GNP[c("Korea", "Nepal")]

Korea Nepal 
 2090   960

In [43]:
v1 <- c(1, 5, 7, 8, 9)
v1

[1] 1 5 7 8 9

In [44]:
v1[2] <- 3

In [45]:
v1

[1] 1 3 7 8 9

In [46]:
v1[c(1, 5)] <- c(10, 20)

In [47]:
v1

[1] 10  3  7  8 20

In [48]:
d <- c(1, 4, 3, 7, 8)
d

[1] 1 4 3 7 8

In [49]:
2 * d

[1]  2  8  6 14 16

In [50]:
d * 2

[1]  2  8  6 14 16

In [52]:
d

[1] 1 4 3 7 8

In [51]:
d - 5
# broadcasting 효과로 전체에 대한 값이 연산됨

[1] -4 -1 -2  2  3

In [53]:
3 * d + 4

[1]  7 16 13 25 28

In [54]:
x <- c(1, 2, 3)
y <- c(4, 5, 6)
x + y
x * y
z <- x + y
z
# 벡터와 벡터를 연산 시, 대응되는 위치에 있는 값끼리의 연산으로 변경되어 실행

[1] 5 7 9

[1]  4 10 18

[1] 5 7 9

In [56]:
d <- c(1:10)
d

[1]  1  2  3  4  5  6  7  8  9 10

In [57]:
sum(d)

[1] 55

In [58]:
sum(d * 2)

[1] 110

In [60]:
length(d)

[1] 10

In [61]:
mean(d[1:5])

[1] 3

In [62]:
max(d)

[1] 10

In [63]:
min(d)

[1] 1

In [65]:
sort(d, F)

[1]  1  2  3  4  5  6  7  8  9 10

In [66]:
sort(d, T)

[1] 10  9  8  7  6  5  4  3  2  1

In [67]:
v.1 <- median(d)
v.1

[1] 5.5

In [68]:
v2 <- sum(d)/length(d)
v2

[1] 5.5

In [69]:
sort(d)
# 기본 ascending = False이기에 그냥 sort대체도 가능

[1]  1  2  3  4  5  6  7  8  9 10

In [70]:
d <- c(1:10)
d

[1]  1  2  3  4  5  6  7  8  9 10

In [75]:
sort(d, F)

[1]  1  2  3  4  5  6  7  8  9 10

In [77]:
d <- 1:9
d

[1] 1 2 3 4 5 6 7 8 9

In [78]:
d >= 5

[1] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE

In [79]:
d[d > 5]

[1] 6 7 8 9

In [80]:
sum(d[d > 5])

[1] 30

In [81]:
condi <- d  > 5 & d < 8
d[condi]

[1] 6 7

In [82]:
ds <- c(90, 85, 70, 84)
ds

[1] 90 85 70 84

In [83]:
my.info = list(name='Tom', age=60, status=TRUE, score=ds)

In [84]:
my.info

$name
[1] "Tom"

$age
[1] 60

$status
[1] TRUE

$score
[1] 90 85 70 84

In [86]:
my.info['score']

$score
[1] 90 85 70 84

In [88]:
my.info$score

[1] 90 85 70 84

In [89]:
my.info[1]

$name
[1] "Tom"

In [90]:
my.info$name

[1] "Tom"

In [91]:
my.info[4]

$score
[1] 90 85 70 84

In [93]:
sum(my.info[4])

ERROR: Error in sum(my.info[4]): invalid 'type' (list) of argument


In [94]:
# 리스트에서 원소를 선택할 때는 2중 대괄호
d[[4]]

[1] 4

In [98]:
mean(my.info[[4]])

[1] 82.25

In [99]:
mean(my.info$score)

[1] 82.25

In [92]:
my.info[[4]]

[1] 90 85 70 84

In [100]:
bt <- c('A', 'B', 'B', 'O', 'AB', 'A')
fac <- factor(bt)
fac

[1] A  B  B  O  AB A 
Levels: A AB B O

In [101]:
bt

[1] "A"  "B"  "B"  "O"  "AB" "A"

In [102]:
fac

[1] A  B  B  O  AB A 
Levels: A AB B O

In [103]:
bt[5]

[1] "AB"

In [104]:
fac[5]

[1] AB
Levels: A AB B O

In [106]:
class(fac)

[1] "factor"

In [107]:
levels(fac)

[1] "A"  "AB" "B"  "O"

In [109]:
as.integer(fac)
# 팩터의 타입을 정수로 바꿔서 출력

[1] 1 3 3 4 2 1

In [111]:
fac[7] <- 'B'
fac

[1] A  B  B  O  AB A  B 
Levels: A AB B O

In [112]:
fac[8] <- 'C'
fac

Warning message in `[<-.factor`(`*tmp*`, 8, value = "C"):
"invalid factor level, NA generated"


[1] A    B    B    O    AB   A    B    <NA>
Levels: A AB B O

In [113]:
25 + 99

[1] 124

In [116]:
levels(fac[2])

[1] "A"  "AB" "B"  "O"

In [117]:
2 * ( 3 + 4)

[1] 14

In [118]:
(7-4) * 3

[1] 9

In [119]:
1256 %% 7

[1] 3

In [120]:
1976 / 24

[1] 82.33333

In [121]:
pi <- 3.14
ax <- c(10, 12, 15)
for(i in 1:3){
    cat("반지름이 ", ax[i], '인 원의 면적 : ', pi*(ax[i] ^ 2), "\n")
}

반지름이  10 인 원의 면적 :  314 
반지름이  12 인 원의 면적 :  452.16 
반지름이  15 인 원의 면적 :  706.5 


In [122]:
vc.2 <- seq(100, 200, 2)
vc.2

[1] 100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136
[20] 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174
[39] 176 178 180 182 184 186 188 190 192 194 196 198 200

In [123]:
d <- 1:200
d

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
[109] 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
[127] 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
[145] 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
[163] 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
[181] 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
[199] 199 200

In [124]:
d[10]

[1] 10

In [125]:
d[190:200]

[1] 190 191 192 193 194 195 196 197 198 199 200

In [126]:
d[d%%2 == 1]

[1]   1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
 [19]  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
 [37]  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 [55] 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 [73] 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 [91] 181 183 185 187 189 191 193 195 197 199

In [127]:
d[d%%3 ==0]

[1]   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54  57
[20]  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108 111 114
[39] 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171
[58] 174 177 180 183 186 189 192 195 198

In [129]:
d.20 <- d[1:20]
d.20

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [131]:
d.20[-5]

[1]  1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [132]:
d.20[-c(5, 7, 9)]

[1]  1  2  3  4  6  8 10 11 12 13 14 15 16 17 18 19 20

In [133]:
d1 <- 1:50
d2 <- 51:100
d1

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

In [134]:
d2

[1]  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69
[20]  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
[39]  89  90  91  92  93  94  95  96  97  98  99 100

In [135]:
d1 + d2

[1]  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86  88
[20]  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120 122 124 126
[39] 128 130 132 134 136 138 140 142 144 146 148 150

In [136]:
d2 - d1

[1] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
[26] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50

In [137]:
d1 * d2

[1]   51  104  159  216  275  336  399  464  531  600  671  744  819  896  975
[16] 1056 1139 1224 1311 1400 1491 1584 1679 1776 1875 1976 2079 2184 2291 2400
[31] 2511 2624 2739 2856 2975 3096 3219 3344 3471 3600 3731 3864 3999 4136 4275
[46] 4416 4559 4704 4851 5000

In [139]:
abs(d1-d2)

[1] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
[26] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50

In [140]:
d2 / d1

[1] 51.000000 26.000000 17.666667 13.500000 11.000000  9.333333  8.142857
 [8]  7.250000  6.555556  6.000000  5.545455  5.166667  4.846154  4.571429
[15]  4.333333  4.125000  3.941176  3.777778  3.631579  3.500000  3.380952
[22]  3.272727  3.173913  3.083333  3.000000  2.923077  2.851852  2.785714
[29]  2.724138  2.666667  2.612903  2.562500  2.515152  2.470588  2.428571
[36]  2.388889  2.351351  2.315789  2.282051  2.250000  2.219512  2.190476
[43]  2.162791  2.136364  2.111111  2.086957  2.063830  2.041667  2.020408
[50]  2.000000

In [141]:
sum(d1)
sum(d2)

[1] 1275

[1] 3775

In [143]:
max(d2)
min(d2)

[1] 100

[1] 51

In [144]:
d.1.mean <- mean(d1)
d.2.mean <- mean(d2)

In [145]:
d.2.mean - d.1.mean

[1] 50

In [146]:
sort(d1, T)

[1] 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
[26] 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1

In [147]:
d3 <- c(d1[1:10], d2[1:10])
d3

[1]  1  2  3  4  5  6  7  8  9 10 51 52 53 54 55 56 57 58 59 60

In [149]:
a <- c("Korea", "Japan", "China", "Korea", "India", "China", "Korea")
f <- factor(a)

In [150]:
f

[1] Korea Japan China Korea India China Korea
Levels: China India Japan Korea

In [151]:
f[[4]]

[1] Korea
Levels: China India Japan Korea

In [153]:
levels(f[[4]])

[1] "China" "India" "Japan" "Korea"

In [154]:
class(f[[4]])

[1] "factor"

In [156]:
f[[4]]

[1] Korea
Levels: China India Japan Korea

In [155]:
as.integer(f[[4]])

[1] 4

In [158]:
2 + 3
# 

[1] 5

In [159]:
(3 + 6) * 8

[1] 72

In [160]:
2 ^ 3

[1] 8

In [161]:
log(10, 10)

[1] 1

In [163]:
log(10) + 5

[1] 7.302585

In [164]:
log(10, 10) + 5

[1] 6

In [165]:
sqrt(25)

[1] 5

In [166]:
max(5, 3, 2)

[1] 5

In [169]:
factorial(5)

[1] 120

In [170]:
job.type <- "A"
if(job.type == 'B'){
    bouns <- 200
}else {
    bonus <- 100
}
bonus

[1] 100

In [171]:
job.type <- 'A'
if(job.type == 'B'){
    bonus <- 200
}else {
    bonus <- 100
}
bonus

[1] 100

In [173]:
a <- 10
if(a < 5){
    pinrt(a)
}else {
    print(a * 10)
    print(a / 10)
}

[1] 100
[1] 1


In [174]:
# and
a <- 10
b <- 20
if(a > 5 & b > 5){
    a + b
}

[1] 30

In [175]:
# or
if(a > 5 | b > 30){
    a * b
}

[1] 200

In [180]:
a <- 10
if(a < 5){
    print(a)
}else {
    print(a * 10)
    print(a / 10)
}

[1] 100
[1] 1


In [181]:
a
a
a

[1] 10

[1] 10

[1] 10

In [183]:
a <- 10
b <- 20

if(a > 5){
    c <- a
}else {
    c <- b
}
a
b
c

[1] 10

[1] 20

[1] 10

In [185]:
ifelse(a>5, a, b)
a 
b
c
# 반환 타입을 위와 같이 c에 대입하거나, 변수에 대압하지 않아도 됨

[1] 10

[1] 10

[1] 20

[1] 10

In [186]:
score <- 100
if(score > 90){
    grade <- 'A'
}else if(score > 80){
    grade <- 'B'
}else if(score > 70){
    grade <- 'C'
}else if(score > 60){
    grade <- 'D'
}else if(score > 50){
    grade <- 'F'
}
grade

[1] "A"

In [190]:
price <- 1000000
if(price >= 300000){
    promotion <- "7%"
}else if(price >= 200000 & price <= 300000){
    promotion <- "5%"
}else if(price >= 100000 & price <= 200000){
    promotion <- "3%"
}else if(price < 100000){
    promotion <- "1%"
}
price
promotion

[1] 1e+06

[1] "7%"

In [192]:
for(i in 1:5){
    print("*")
}

[1] "*"
[1] "*"
[1] "*"
[1] "*"
[1] "*"


In [193]:
for(i in 6:10){
    print(i)
}

[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [195]:
for(i in 1:9){
    cat("9 * ", i, "=", 9 * i, "\n")
}

9 *  1 = 9 
9 *  2 = 18 
9 *  3 = 27 
9 *  4 = 36 
9 *  5 = 45 
9 *  6 = 54 
9 *  7 = 63 
9 *  8 = 72 
9 *  9 = 81 


In [196]:
for(i in 1:20){
    if(i%%2 == 0){
        cat(i, '')
    }
}

2 4 6 8 10 12 14 16 18 20 

In [197]:
sum <- 0
for(i in 1:100){
    sum <- sum + i
}
print(sum)

[1] 5050


In [198]:
nrow

function (x) 
dim(x)[1L]
<bytecode: 0x000001a9ae578898>
<environment: namespace:base>

In [199]:
norow <- nrow(iris)
mylabel = c()
for(i in 1:norow){
    if(iris$Petal.Length[i] <= 1.6){
        mylabel[i] <- 'L'
    } else if(iris$Petal.Length[i] <= 5.1){
        mylabel[i] <- 'H'
    } else {
        mylabel[i] <- 'M'
    }
}
print(mylabel)
newds <- data.frame(iris$Petal.Length, mylabel)
head(newds)

  [1] "L" "L" "L" "L" "L" "H" "L" "L" "L" "L" "L" "L" "L" "L" "L" "L" "L" "L"
 [19] "H" "L" "H" "L" "L" "H" "H" "L" "L" "L" "L" "L" "L" "L" "L" "L" "L" "L"
 [37] "L" "L" "L" "L" "L" "L" "L" "L" "H" "L" "L" "L" "L" "L" "H" "H" "H" "H"
 [55] "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H"
 [73] "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "H"
 [91] "H" "H" "H" "H" "H" "H" "H" "H" "H" "H" "M" "H" "M" "M" "M" "M" "H" "M"
[109] "M" "M" "H" "M" "M" "H" "H" "M" "M" "M" "M" "H" "M" "H" "M" "H" "M" "M"
[127] "H" "H" "M" "M" "M" "M" "M" "H" "M" "M" "M" "M" "H" "M" "M" "H" "H" "M"
[145] "M" "M" "H" "M" "M" "H"


iris.Petal.Length mylabel
1 1.4               L      
2 1.4               L      
3 1.3               L      
4 1.5               L      
5 1.4               L      
6 1.7               H

In [200]:
colnames(iris)

[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

In [203]:
apply(iris[, 1:4], 1, mean)

[1] 2.550 2.375 2.350 2.350 2.550 2.850 2.425 2.525 2.225 2.400 2.700 2.500
 [13] 2.325 2.125 2.800 3.000 2.750 2.575 2.875 2.675 2.675 2.675 2.350 2.650
 [25] 2.575 2.450 2.600 2.600 2.550 2.425 2.425 2.675 2.725 2.825 2.425 2.400
 [37] 2.625 2.500 2.225 2.550 2.525 2.100 2.275 2.675 2.800 2.375 2.675 2.350
 [49] 2.675 2.475 4.075 3.900 4.100 3.275 3.850 3.575 3.975 2.900 3.850 3.300
 [61] 2.875 3.650 3.300 3.775 3.350 3.900 3.650 3.400 3.600 3.275 3.925 3.550
 [73] 3.800 3.700 3.725 3.850 3.950 4.100 3.725 3.200 3.200 3.150 3.400 3.850
 [85] 3.600 3.875 4.000 3.575 3.500 3.325 3.425 3.775 3.400 2.900 3.450 3.525
 [97] 3.525 3.675 2.925 3.475 4.525 3.875 4.525 4.150 4.375 4.825 3.400 4.575
[109] 4.200 4.850 4.200 4.075 4.350 3.800 4.025 4.300 4.200 5.100 4.875 3.675
[121] 4.525 3.825 4.800 3.925 4.450 4.550 3.900 3.950 4.225 4.400 4.550 5.025
[133] 4.250 3.925 3.925 4.775 4.425 4.200 3.900 4.375 4.450 4.350 3.875 4.550
[145] 4.550 4.300 3.925 4.175 4.325 3.950

In [205]:
apply(iris[, 1:4], 2, mean)

Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
    5.843333     3.057333     3.758000     1.199333

In [207]:
colMeans(iris[, 1:4])

Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
    5.843333     3.057333     3.758000     1.199333

In [208]:
score <- c(76, 84, 69, 50, 95, 60, 82, 71, 88, 84)
which(score == 69)

[1] 3

In [209]:
which(score >= 85)

[1] 5 9

In [210]:
score[which(score == max(score))]

[1] 95

In [212]:
score[which.max(scorbe)]

[1] 95

In [213]:
score[which.min(score)]

[1] 50

In [214]:
which.min(score)

[1] 4

In [215]:
score <- c(76, 84, 69, 50, 95, 60, 82, 71, 88, 84)
which(score < 60)

[1] 4

In [218]:
score[which(score <= 60)] <- 61

In [219]:
score

[1] 76 84 69 61 95 61 82 71 88 84

In [220]:
which(score > 80)

[1]  2  5  7  9 10

In [221]:
score_cx <- score[which(score > 80)]

In [222]:
score_cx

[1] 84 95 82 88 84

In [224]:
score <- c(76, 84, 69, 50, 96, 60, 82, 71, 88, 84)
score

[1] 76 84 69 50 96 60 82 71 88 84

In [225]:
score[score >= 80]

[1] 84 96 82 88 84

In [226]:
subset(score, score >= 80)

[1] 84 96 82 88 84

In [228]:
idx <- which(iris$Petal.Length >= 5.0)
idx

[1]  78  84 101 102 103 104 105 106 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120 121 123 125 126 129 130 131 132 133 134 135 136 137 138 140 141 142
[39] 143 144 145 146 147 148 149 150

In [230]:
iris.big = iris[idx, ]

In [231]:
iris.big

Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
78  6.7          3.0         5.0          1.7         versicolor
84  6.0          2.7         5.1          1.6         versicolor
101 6.3          3.3         6.0          2.5         virginica 
102 5.8          2.7         5.1          1.9         virginica 
103 7.1          3.0         5.9          2.1         virginica 
104 6.3          2.9         5.6          1.8         virginica 
105 6.5          3.0         5.8          2.2         virginica 
106 7.6          3.0         6.6          2.1         virginica 
108 7.3          2.9         6.3          1.8         virginica 
109 6.7          2.5         5.8          1.8         virginica 
110 7.2          3.6         6.1          2.5         virginica 
111 6.5          3.2         5.1          2.0         virginica 
112 6.4          2.7         5.3          1.9         virginica 
113 6.8          3.0         5.5          2.1         virginica 
114 5.7          2.5         5.0          2.0         virginica 
115 5.8          2.8         5.1          2.4         virginica 
116 6.4          3.2         5.3          2.3         virginica 
117 6.5          3.0         5.5          1.8         virginica 
118 7.7          3.8         6.7          2.2         virginica 
119 7.7          2.6         6.9          2.3         virginica 
120 6.0          2.2         5.0          1.5         virginica 
121 6.9          3.2         5.7          2.3         virginica 
123 7.7          2.8         6.7          2.0         virginica 
125 6.7          3.3         5.7          2.1         virginica 
126 7.2          3.2         6.0          1.8         virginica 
129 6.4          2.8         5.6          2.1         virginica 
130 7.2          3.0         5.8          1.6         virginica 
131 7.4          2.8         6.1          1.9         virginica 
132 7.9          3.8         6.4          2.0         virginica 
133 6.4          2.8         5.6          2.2         virginica 
134 6.3          2.8         5.1          1.5         virginica 
135 6.1          2.6         5.6          1.4         virginica 
136 7.7          3.0         6.1          2.3         virginica 
137 6.3          3.4         5.6          2.4         virginica 
138 6.4          3.1         5.5          1.8         virginica 
140 6.9          3.1         5.4          2.1         virginica 
141 6.7          3.1         5.6          2.4         virginica 
142 6.9          3.1         5.1          2.3         virginica 
143 5.8          2.7         5.1          1.9         virginica 
144 6.8          3.2         5.9          2.3         virginica 
145 6.7          3.3         5.7          2.5         virginica 
146 6.7          3.0         5.2          2.3         virginica 
147 6.3          2.5         5.0          1.9         virginica 
148 6.5          3.0         5.2          2.0         virginica 
149 6.2          3.4         5.4          2.3         virginica 
150 5.9          3.0         5.1          1.8         virginica

In [232]:
score <- c(60, 40, 95, 80)
names(score) <- c("John", "Jane", "Tom", "David")
score

John  Jane   Tom David 
   60    40    95    80

In [238]:
which(score == max(score))

Tom 
  3

In [240]:
names(score)[which(score == max(score))]

[1] "Tom"

In [243]:
z = matrix(1:20, nrow=4, ncol=5)
z

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [244]:
z = matrix(1:20, nrow=4, ncol=5, byrow=T)
z
# 행 방향 데이터 채우기

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20

In [245]:
x <- 1:4
y <- 5:8
z <- matrix(1:20, nrow=4, ncol=5)

In [247]:
m1 <- cbind(x, y)
m1

x y
[1,] 1 5
[2,] 2 6
[3,] 3 7
[4,] 4 8

In [248]:
rbind(x, y)

[,1] [,2] [,3] [,4]
x 1    2    3    4   
y 5    6    7    8

In [249]:
cbind(z, x)

x
[1,] 1 5  9 13 17 1
[2,] 2 6 10 14 18 2
[3,] 3 7 11 15 19 3
[4,] 4 8 12 16 20 4

In [250]:
rbind(z , x)

Warning message in rbind(z, x):
"number of columns of result is not a multiple of vector length (arg 2)"


[,1] [,2] [,3] [,4] [,5]
  1    5     9   13   17  
  2    6    10   14   18  
  3    7    11   15   19  
  4    8    12   16   20  
x 1    2     3    4    1

In [251]:
x <- c(1, 2, 3, 4)
y <- c(5, 6, 7, 8)
cbind(x, y)

x y
[1,] 1 5
[2,] 2 6
[3,] 3 7
[4,] 4 8

In [253]:
m <- matrix(1:8, nrow=4, ncol=2)
m

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

In [256]:
rownames(m) <- c(1, 2, 3, 4)

In [257]:
colnames(m) <- c("x", "y")

In [258]:
m

x y
1 1 5
2 2 6
3 3 7
4 4 8

In [260]:
x <- 1:4
y <- 5:8
io <- rbind(x, y)

In [263]:
rbind(io, x)

[,1] [,2] [,3] [,4]
x 1    2    3    4   
y 5    6    7    8   
x 1    2    3    4

In [264]:
m4 <- cbind(x, y)

In [265]:
m4

x y
[1,] 1 5
[2,] 2 6
[3,] 3 7
[4,] 4 8

In [266]:
m5 <- cbind(io, x, y)

Warning message in cbind(io, x, y):
"number of rows of result is not a multiple of vector length (arg 2)"


In [267]:
m5

x y
x 1 2 3 4 1 5
y 5 6 7 8 2 6

In [268]:
z <- matrix(1:20, nrow=4, ncol=5)

In [269]:
z

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [270]:
z[2, 3]

[1] 10

In [271]:
z[1, 4]

[1] 13

In [272]:
z[2, ]

[1]  2  6 10 14 18

In [274]:
z[, 4]

[1] 13 14 15 16

In [275]:
z <- matrix(1:20, nrow=4, ncol=5)
z

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [276]:
z[2, 1:3]

[1]  2  6 10

In [277]:
z[1, c(1, 2, 4)]

[1]  1  5 13

In [278]:
z[1:2, ]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18

In [279]:
z[, c(1, 4)]

[,1] [,2]
[1,] 1    13  
[2,] 2    14  
[3,] 3    15  
[4,] 4    16

In [280]:
score <- matrix(c(90, 85, 69, 78, 85, 96, 49, 95, 90, 80, 70, 60), nrow=4)

In [281]:
score

[,1] [,2] [,3]
[1,] 90   85   90  
[2,] 85   96   80  
[3,] 69   49   70  
[4,] 78   95   60

In [284]:
rownames(score) <- c("layla","noa","focalors","seniya")
colnames(score) <- c("science", "math", "Show")

In [285]:
score

science math Show
layla    90      85   90  
noa      85      96   80  
focalors 69      49   70  
seniya   78      95   60

In [289]:
score['layla','math']

[1] 85

In [291]:
score['noa', c('math', 'science')]

math science 
     96      85

In [292]:
score['noa', ]

science    math    Show 
     85      96      80

In [293]:
score[, 'Show']

layla      noa focalors   seniya 
      90       80       70       60

In [294]:
rownames(score)

[1] "layla"    "noa"      "focalors" "seniya"

In [295]:
colnames(score)

[1] "science" "math"    "Show"

In [296]:
colnames(score)[2]

[1] "math"